# Intel CPU Crawler Configuration
# 
# This configuration file controls all aspects of the Intel CPU crawling process.
# Optimized for extracting power modeling data from US English specification pages.

# =============================================================================
# CRAWLING TARGETS
# =============================================================================
# Base URLs to start crawling from (US English only)
# These are the main processor category pages that contain links to individual CPU specs
base_urls:
  # - "https://www.intel.com/content/www/us/en/products/details/processors.html"
  - "https://www.intel.com/content/www/us/en/products/details/processors/core-ultra.html"
  - "https://www.intel.com/content/www/us/en/products/details/processors/core.html"

  # Temporarily disabled Xeon crawling
  # - "https://www.intel.com/content/www/us/en/products/details/processors/xeon.html"

# =============================================================================
# REQUEST CONFIGURATION
# =============================================================================
# HTTP request settings to avoid being blocked
request_timeout: 30      # Timeout in seconds for each request
max_retries: 3          # Number of retries for failed requests
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# SQLite database settings optimized for power modeling applications
database:
  enabled: true                                    # Enable database storage
  path: "data/intel_cpu_power_specs.db"          # Database file location
  backup_on_start: true                          # Create backup before crawling
  export_for_modeling: true                      # Enable modeling data export

